<?php

namespace Container71YrTkB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Loader_NativeFilesystemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.loader.native_filesystem' shared service.
     *
     * @return \Twig\Loader\FilesystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig.loader.native_filesystem'] = $instance = new \Twig\Loader\FilesystemLoader([], 'Z:\\test_projet');

        $instance->addPath('Z:\\test_projet\\vendor\\easycorp\\easyadmin-bundle\\src/../templates/', 'ea');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\ux-twig-component/templates', 'TwigComponent');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\ux-twig-component/templates', '!TwigComponent');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\security-bundle/Resources/views', 'Security');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\security-bundle/Resources/views', '!Security');
        $instance->addPath('Z:\\test_projet\\vendor\\doctrine\\doctrine-bundle/templates', 'Doctrine');
        $instance->addPath('Z:\\test_projet\\vendor\\doctrine\\doctrine-bundle/templates', '!Doctrine');
        $instance->addPath('Z:\\test_projet\\vendor\\easycorp\\easyadmin-bundle/templates', 'EasyAdmin');
        $instance->addPath('Z:\\test_projet\\vendor\\easycorp\\easyadmin-bundle/templates', '!EasyAdmin');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\maker-bundle/templates', 'Maker');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\maker-bundle/templates', '!Maker');
        $instance->addPath('Z:\\test_projet\\vendor\\doctrine\\doctrine-migrations-bundle/templates', 'DoctrineMigrations');
        $instance->addPath('Z:\\test_projet\\vendor\\doctrine\\doctrine-migrations-bundle/templates', '!DoctrineMigrations');
        $instance->addPath('Z:\\test_projet/templates');
        $instance->addPath('Z:\\test_projet\\vendor\\symfony\\twig-bridge/Resources/views/Form');

        return $instance;
    }
}
