<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCCsjofb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCCsjofb/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCCsjofb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCCsjofb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCCsjofb\App_KernelProdContainer([
    'container.build_hash' => 'CCsjofb',
    'container.build_id' => '6daeab1f',
    'container.build_time' => 1758593380,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCCsjofb');
