<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acces_gestion_equipes' => [parent::class, 'acces_gestion_equipes', null, 16],
        "\0".parent::class."\0".'acces_gestion_utilisateurs' => [parent::class, 'acces_gestion_utilisateurs', null, 16],
        "\0".parent::class."\0".'bureau' => [parent::class, 'bureau', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'derniere_connexion' => [parent::class, 'derniere_connexion', null, 16],
        "\0".parent::class."\0".'email_perso' => [parent::class, 'email_perso', null, 16],
        "\0".parent::class."\0".'email_pro' => [parent::class, 'email_pro', null, 16],
        "\0".parent::class."\0".'fonction' => [parent::class, 'fonction', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'identifiant' => [parent::class, 'identifiant', null, 16],
        "\0".parent::class."\0".'metier' => [parent::class, 'metier', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'acces_gestion_equipes' => [parent::class, 'acces_gestion_equipes', null, 16],
        'acces_gestion_utilisateurs' => [parent::class, 'acces_gestion_utilisateurs', null, 16],
        'bureau' => [parent::class, 'bureau', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'derniere_connexion' => [parent::class, 'derniere_connexion', null, 16],
        'email_perso' => [parent::class, 'email_perso', null, 16],
        'email_pro' => [parent::class, 'email_pro', null, 16],
        'fonction' => [parent::class, 'fonction', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'identifiant' => [parent::class, 'identifiant', null, 16],
        'metier' => [parent::class, 'metier', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
